### ISSUE TITLE
Using the official container

### ISSUE THREAD

**Issue by begriffs** [suzel/docker-postgrest#1]
Hey @suzel thanks for providing this repo to help people out during all that time we didn't have an official postgrest container. Today I released https://hub.docker.com/r/begriffs/postgrest and I'm wondering if you could add a note on your repo to point people to that one? It'll make my maintenance job easier if people are running a standard config.

Also would love your opinion about ways to improve the official Dockerfile.

**Comment by suzel** [comment]
https://github.com/suzel/docker-postgrest#resources

**Comment by begriffs** [comment]
Thanks!
